### ISSUE TITLE
How do you pass bulk usernames in?

### ISSUE THREAD

**Issue by FrozenBeard** [Shadowwolf97/Minecraft-UUID-Utils#12]
I have 4000 users prior to 1.7 I need to convert to UUID's; I know that bulk lokoups can be done, can I do it with this script?

**Comment by endercrest** [comment]
At this time. The Utility does not support bulk look ups. I can look into implementing it in the future. 

At this very moment, you will need to do an individual request. The only problem you will run into is Mojang has a limit of 600 requests per 10 minutes (http://wiki.vg/Mojang_API).

**Comment by endercrest** [comment]
This has now been implemented. Cheers, :)
